name: "Docker: Docker Hub"

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main_access_token ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main_access_token ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: liuzy/agentgpt

jobs:env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}

jobs:
  build_and_push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$REPOSITORY_NAME:latest

      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/$REPOSITORY_NAME:latest
