name: Generate Sponsors README

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Print Git info
        run: |
          echo "Git version:"
          git --version
          echo "Remote URL:"
          git remote -v

      - name: Generate Sponsors ğŸ’–
        uses: JamesIves/github-sponsors-readme-action@v1.4.0
        with:
          token: ${{ secrets.SPONSOR_WORKFLOW_PAT }}
          file: 'README.md'
          minimum: 1399

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.SPONSOR_WORKFLOW_PAT }}
        with:
          branch: "workflow/sponsors"
          title: "ğŸ¤– Update Sponsors"
          commit-message: "ğŸ¤– Update Sponsors"
          body: "ğŸ¤– Automated pull request created by sponsors action"
          labels: "documentation"
